image: ruby:2.6

variables:
  JEKYLL_ENV: production

cache:
  paths:
  - vendor/

pages:
  stage: deploy
  script:
    - curl -o _data/regnum.json https://scripts.drachenwald.sca.org/json/regnum-officers-box.json
    - bundle install --path vendor
    - JEKYLL_ENV=staging bundle exec jekyll build -d public
  artifacts:
    expire_in: 1 hour
    paths:
      - public
  only:
    - staging


deploy:
  stage: deploy
  script:
    - curl -o _data/regnum.json https://scripts.drachenwald.sca.org/json/regnum-officers-box.json
    - bundle install --path vendor
    - bundle exec jekyll build -d public
    - /usr/bin/lftp -u $FTPUSER,$FTPPASS -e 'set ssl:verify-certificate false ; mirror --reverse --verbose --delete --ignore-time --exclude=.protect public / ; quit' $FTPSERVER
    - ./_ci/cf-clear.sh
  artifacts:
    expire_in: 1 hour
    paths:
      - public
  only:
    - main